### ISSUE TITLE
How to attach custom made extension to safe browser

### ISSUE THREAD

**Issue by xiaobai-op** [SafeExamBrowser/seb-win-refactoring#100]
I am creating an extension in the firefox environemnt, would like to attach it to the safe browser.
can anyone help me out with the steps to do so!

**Comment by dbuechel** [comment]
SEB 3.x doesn't use Firefox as integrated browser engine anymore, instead we switched to Chromium / the Chromium Embedded Framework resp CefSharp. We also don't support browser extensions at the moment.

Could you please elaborate a bit more about your scenario and use cases, so that we might keep this open as a feature request? Otherwise we'd need to close the issue for now, as our schedule is already more than full with other feature requests.

**Comment by xiaobai-op** [comment]
I will go with a different approach as my use case required an extension feature, Thanks for the help!
