### ISSUE TITLE
Videos do not start using SEB 3.2.0

### ISSUE THREAD

**Issue by GRRRR11** [SafeExamBrowser/seb-win-refactoring#102]
If videos (MP4) are integrated in an exam with ILIAS, they do not start under SEB 3.1. Not even if the videos were produced using a free codec (x264, x265).
The videos have been inserted into the questions using the ILIAS page editor. The "video image" is displayed and you can click on the start button, but the video does not start, but continues to load indefinitely.
These problems do not exist under SEB 2.4.

1. create a test/question in ILIAS
2. add an MP4 video via "Edit page"
3. put the test online.
4. start the test via SEB.
5. start video.
6. watch it not start

**Expected Behavior**
Actually, the videos should start and run smoothly, as they did until SEB 2.4.1.

**Version Information**
 - OS: Windows 10 Enterprise, Version 1909
 - SEB-Version 3.2.0

**Comment by dbuechel** [comment]
Chromium / CEF (the browser engine we use in SEB 3.x) does not support proprietary codecs, thus you'll need to use a free codec like WebM. An overview over which audio and video codecs the current SEB version supports can be obtained by loading https://html5test.com/ within SEB.

**Comment by fishfree** [comment]
@danschlet That's very awful for average users, who usually use the much more popular H.264 MP4 files.

**Comment by danschlet** [comment]
I agree. Unfortunately this is a limitation of the CEF (CefSharp) browser engine because of its open source nature and the complicated licensing terms of the H.264 video and especially AAC audio codecs (see the [CefSharp release notes](https://github.com/cefsharp/CefSharp/releases) for more information). We even inquired if we could add the H.264 codec to CefSharp or pay someone to do it, but it seems almost impossible to achieve that (if someone reading this can do it, contact us).

The only realistic chance to get support for H.264 MP4 files in the future is when Microsofts adds all missing functionality required for SEB to its WebView2 browser engine, then we can switch to it in SEB. WebView2 supports H.264 and other commercially licensed codecs.
