### ISSUE TITLE
SEB configuration

### ISSUE THREAD

**Issue by paaaj** [SafeExamBrowser/seb-win-refactoring#201]
Hi! Whenever I click "download configuration" on Moodle, I am always redirected to Modify Setup where I have the option to uninstall SEB. Please help.

**Comment by dbuechel** [comment]
Try to manually uninstall SEB via the Windows control panel, then reboot your machine and reinstall the latest version of SEB for Windows.

**Comment by WilliamDelamare** [comment]
Hi!
I have a couple of students (over 300) with the same problem : opening a `config.seb` file leads to the `Modify Setup` dialog (for uninstalling the program).

Did you manage to solve it?
I see the issue is closed, but we tried (more than a few times) uninstalling via several ways (control panel, program manager, etc), but they all go through the standard uninstall program anyway.
No change.

Note : The students are using the latest (3.4.1.505), even the ones without this problem.

**Comment by dbuechel** [comment]
You can try to uninstall SEB, manually remove the file type association (see e.g. https://www.raymond.cc/blog/how-unassociate-windows-vista-7-file-type/) and then reinstall SEB.

**Comment by WilliamDelamare** [comment]
We tried solution number 7 in your link, and it worked.

Thanks!
