### ISSUE TITLE
SEB password dialog not properly focused

### ISSUE THREAD

**Issue by mattimagg** [SafeExamBrowser/seb-win-refactoring#323]
**Operating System**
Windows 10.

**Safe Exam Browser Version**
3.1.1.250 for Windows.

**Test Environment**
Inspera.

**Bug description**
When the "Start test in Safe Exam Browser" button has been pressed, a dialog appears, ready to receive the SEB password. But although the cursor can be seen blinking in the text box, the dialog has lost focus. So when the candidates try to enter the password, nothing happens. They actually have to click inside the text box to give the window/text box focus and be able to type the password.

**Steps to reproduce**
1.  Open any browser in Windows and navigate to hi.inspera.com and press "Click here to get ready" button for a test that has been created and scheduled.
2.  Click the button "Start test in Safe Exam Browser".
3.  Try to type SEB password into text box. Not possible unless the window is actually clicked first.

**Expected behaviour**
When a cursor is blinking inside a text box, a user expects that the text box is ready to receive input and that the window does not have to be clicked first.

Best regards,
Matthias Magnusson
University of Iceland
mattim@hi.is

**Comment by jeroenhabets** [comment]
For what it's worth: I have been encountering this as well but suspected it might be caused by the fact that I'm running SEB Win inside a VirtualBox VM. I suppose I could help testing a fix.

**Comment by mattimagg** [comment]
Thanks, Jeroen, but we are not running VMs. This behaviour began in one of
the versions coming out in 2020, I think. It seems to me that the
developers need to end the dialog display process by finding the window and
giving it input focus.

Best regards,
Matthias

mán., 10. jan. 2022 kl. 20:09 skrifaði jeroenhabets <
***@***.***>:

**Comment by dbuechel** [comment]
Thanks for the report, we'll have a look at it.

**Comment by dbuechel** [comment]
Apologies for the late response, we were extremely busy the last couple of months and did not have the time to investigate this issue sooner.

I was able to reproduce the problem (though not consistently): The root cause appears to be a security mechanism of Windows which prevents applications from "stealing" the input focus from the currently active application. If this happens, the system will highlight that particular application with an orange pulsating color in the taskbar.

As far as I know, there is no workaround for this behavior of the operating system, but please feel free to reopen the issue in case you have further information.
