### ISSUE TITLE
DRM is Necessary to play some content

### ISSUE THREAD

**Issue by e1l1ya** [SafeExamBrowser/seb-win-refactoring#364]
**DRM** is Necessary to play some contents.
when we are trying to load some videos that need DRM, the CDN used to stream videos, send us this error: **you are on privacy mode please turn it off and enable play DRM-controlled content**

**Comment by dbuechel** [comment]
We'd need to know what exactly the underlying issue is. The browser engine (CefSharp resp. CEF) isn't configured to use any "privacy mode", though it may be that there could be some DRM-related configuration values which we don't set (yet). We don't have time to investigate the issue ourselves at the moment, but if you can come up with a pull request or the exact changes we'd need to make then we may be able to integrate a fix in version 3.4.

**Comment by e1l1ya** [comment]
We use **video cipher** as CDN for our videos on website. this CDN will encrypt videos and dont let no one to download it then when browsers try to load this videos use DRM to decrypt and play it. when ever we try to load this video using SEB it shown us the error that i told it befor. we want you to add options in config maker that we can enable or disable DRM.

**Comment by dbuechel** [comment]
Okay, after a quick internet search I've come across the following issue for CEF: https://bitbucket.org/chromiumembedded/cef/issues/1631/add-support-for-widevine-cdm. It appears this is related to the proprietary codec issue which we can't resolve due to licensing issues, so I'll have to mark this as "won't fix" for the moment. But as already stated above, please feel free to reopen the issue in case you have a concrete proposal or even a pull request to enable the functionality you require.
