### ISSUE TITLE
SEB NVDA Support

### ISSUE THREAD

**Issue by acbreceda** [SafeExamBrowser/seb-win-refactoring#428]
Hello,

We are trying to see if an issue we are running into is a known bug that may have been corrected or not. We have been using SEB and are trying to make sure it works with the NVDA Screen Reader. We did add "nvda.exe" and "nvda_slave.exe" to the list of Permitted Processes in the SEB configuration file (under the Applications tab).

However, the only way this does work is if Autostart is checked for these files. This does work great if our users already have and need to use NVDA, but causes issues for any user or machine that doesn't need it. If NVDA is installed on a machine then it launches NVDA even if that user doesn't need it. And if NVDA is not installed, then trying to open SEB gives an error to choose the location of the executable.

Our current version is 2.3 but we have did test this in the updated version of 3.3.2 as well.

Any other method without choosing Autostart, and NVDA can't be used. Is this a known issue/requirement to use NVDA with SEB?

![image-2022-06-16-15-30-28-368](https://user-images.githubusercontent.com/108016156/175081142-c1013093-b0fb-4ba9-be2c-66549f7f1dec.png)

Thank You,
Anthony

**Comment by dbuechel** [comment]
First, we highly recommend to update to the latest official release version of SEB 3.x. Version 2.x is not supported anymore and lacks a lot of important security updates and other improvements.

With respect to SEB 3.x and NVDA: There is an issue in NVDA itself which prevents it from working properly with embedded Chromium browsers, see https://github.com/nvaccess/nvda/issues/8553. The upcoming release version 3.4.0 will contain major accessibility improvements, due to the aforementioned issue however only entirely working with JAWS.

**Comment by acbreceda** [comment]
Hi,

Thank you for the information. We have updated to 3.x and are seeing the same issue of needing to set up the configuration file to auto start the NVDA.exe program. Do you know if that should be the only way to have NVDA work with SEB? Should it work without needing to be checked to autostart? Is it something that could be fixed in version 3.4.0?

**Comment by dbuechel** [comment]
We had to find that both screen readers we are testing (NVDA and JAWS) are not compatible with kiosk mode Create New Desktop. We won't be able to resolve this for SEB 3.4.0, but as a workaround, you can simply use the other kiosk mode (Disable Explorer Shell).
