### ISSUE TITLE
Ctrl+Q quit shortcut doesn't work while WebRTC has the microphone captured

### ISSUE THREAD

**Issue by chrisswan-rm** [SafeExamBrowser/seb-win-refactoring#471]
If you use SEB to view a page that uses WebRTC to record audio, it is not possible to use the Ctrl+Q quit shortcut while the microphone is captured (upon pressing Ctrl+Q, nothing happens). Once the microphone is released Ctrl+Q becomes available again.

You can easily reproduce it using [this](https://www.webrtc-experiment.com/RecordRTC/simple-demos/audio-recording.html) demo page.

- Set this page as the start page in SEB
- Once the page loads, try using Ctrl+Q and observe that it works.
- Now press "Start Recording" and observe that while recording Ctrl+Q does not work.
- Press "Stop Recording" and observe that Ctrl+Q still does not work.
- Press "Release Microphone" and observe that Ctrl+Q works again.

This can be reproduced in the latest SEB 3.4.0 and also 3.3.2 (likely to exist in all versions since the introduction of WebRTC support). 

The obvious workaround is to ensure that the bottom toolbar of SEB is enabled so that there's a visible "Quit" button to press, removing the need to use the shortcut. However this is not always desirable as the toolbar takes up some screen space.

The reason this causes us a problem is because we have a "Speaking" test where the microphone is captured for a relatively long time, and during this time it is not possible to quit SEB (unless we enable the toolbar, which we ideally don't want to do).

**Comment by danschlet** [comment]
You could also use a [quit link](https://safeexambrowser.org/windows/win_usermanual_en.html#ExamPane) placed somewhere conveniently on your web page as a workaround.

**Comment by dbuechel** [comment]
We'll need to investigate the problem, but I suspect this to be an issue in the browser engine. Did you test whether the action center works? It can be activated via WIN+A and would provide another option to quit SEB.

**Comment by chrisswan-rm** [comment]
No, action centre doesn't work either. Win+A works when the microphone is not in use, but doesn't work when it is,

I think the issue seems to be that the key handler in KeyboardHook.cs doesn't work correctly / isn't hit while the microphone is active in CEF, which would explain why none of the usual shortcuts work. Key events are still raised as expected via KeyboardHandler.cs (which captures keyboard events in CEF itself) but that isn't enough because I think the shortcuts like quit, action centre etc. are not handled from there.

**Comment by dbuechel** [comment]
Exactly, they are handled via low level monitoring of the keyboard. This incidentally also was one of the issues we had initially resp. why we couldn't activate WebRTC with the first release of SEB 3.x (see #3 and/or https://bitbucket.org/chromiumembedded/cef/issues/2609/chomium-windows-when-using-own-low-level).

This very much looks like a regression in the upstream CEF or Chromium codebase. Looking at the issue from CEF linked above, I just noted that it is still set to "won't fix" even though WebRTC used to work fine since we activated it, at least until now. We'll see that we can investigate the issue (certainly before the release of version 3.5), at the moment we're unfortunately quite busy with other priorities.

**Comment by dbuechel** [comment]
Due to a change in priorities, we won't be able to investigate the issue for the upcoming release version 3.5.0. Have there been any further insights in the meantime @chrisswan-rm?

**Comment by chrisswan-rm** [comment]
@dbuechel thanks for letting me know. No, we haven't looked into this further; we have told our client that this is a limitation for now (that they cannot use Ctrl+Q to quit when on a part of the exam that uses audio recording).

**Comment by dbuechel** [comment]
Okay, thanks for the feedback. Then we'll leave this open so that we'll hopefully get around to having a look at it for version 3.6.0, albeit that I highly suspect this to be a bug / regression in the browser engine as mentioned above.

**Comment by dbuechel** [comment]
Thanks again for your report and sorry for the delayed tackling of the issue. I am able to reproduce the issue as reported by you above, but am afraid that this very much appears to be a regression somewhere in the browser engine (be it Chromium itself or the Chromium Embedded Framework CEF).

Thus, I currently don't see any option other than waiting and hoping for the best (i.e. that the regression is fixed in the engine asap). But please let me know if there is anything you'd like to investigate further, I'll certainly leave the issue open for now but mark it accordingly as framework bug.
