### ISSUE TITLE
TAB key crashes SEB when "Show taskbar/dock" is disabled

### ISSUE THREAD

**Issue by Krisell** [SafeExamBrowser/seb-win-refactoring#490]
**Describe the Bug**
In SEB 3.4.0, when using the setting to not show the taskbar/dock, using the TAB key a few times causes SEB to crash and quit. See exact steps below.

This is confirmed to only occur when _"Show taskbar/dock"_ is disabled. Perhaps the tab press causes SEB to try to focus a UI item that is not present?

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/25909128/196437504-8cea8a6c-f043-4fbc-91be-d5cb9145adaa.png">

**Steps to Reproduce**
1. Configure SEB to not show taskbar/dock.
2. Start SEB (default page suffices)
3. Press tab a few times. See the links getting highlighted, and after the final link, SEB crashes. Pages with fewer tabbable items will crash earlier.

**Expected Behavior**
Tabbing wraps around. This is done correctly in SEB 3.3.2, and in 3.4.0 when the taskbar is shown (after tabbing through the taskbar items).

**Version Information**
 - OS: Windows 10 Professional, Version 1889
 - SEB-Version: 3.4.0 (Confirmed that bug is _**not**_ present in 3.3.2).

**Comment by dbuechel** [comment]
Thanks a lot for your report. It seems that this bug was introduced with the accessibility features we added in version 3.4.0. We'll see that we can fix the issue for version 3.5.0 at the latest.

**Comment by dbuechel** [comment]
@yolpsoftware Could you please have a look at the issue? I think the problem is that when the taskbar isn't used, it also isn't initialized with the permitted applications and thus the following line causes the IndexOutOfRangeException shown above: https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.UserInterface.Desktop/Windows/Taskbar.xaml.cs#L94
