### ISSUE TITLE
Error 0x80072efe: Failed to execute EXE package. When using WebView2_Bootstrapper

### ISSUE THREAD

**Issue by uqswalk5** [SafeExamBrowser/seb-win-refactoring#497]
Hi Damien,

We are seeing an issue where a number of BYOD  students using Windows 10 and 11 are having problems installing SEB_3.4.0.480 and the install reaches the point where the WebView2_Bootstrapper package is required. 

I have already looked at the discussions at: 

https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/424#discussioncomment-3029818 https://github.com/SafeExamBrowser/seb-win-refactoring/issues/429 

which seem to be a related issue but it is not helping me find a solution for my students.

My students are mostly located in mainland China and are generally using newish PCs. We have been using SEB for 4 years now and have always found a way to get past previous problems but this one has me struggling to offer help.

I am attaching the log files of one student who seems to have the issue. I am afraid I am not super technical but I am the person responsible for helping students prepare to take their exams online. 

Any advive would be very much appreciated. You do a great job there at SEB. 

Best wishes

Stephen

[Bootstrapper error 3.4.0.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/9905483/Bootstrapper.error.3.4.0.txt)

**Comment by dbuechel** [comment]
Most unfortunately, the WebView2 bootstrapper has caused various issues since we had to include it in our setup bundle. As it is a bootstrapper, a stable and working internet connection is required, otherwise the bootstrapper cannot download the actual WebView2 installer itself. It is however unclear to me whether this may be the underlying issue here.

Either way, you should always be able to work around any such issues by manually installing the required runtime dependencies:

1. Install all the required runtime dependencies (as listed in the readme or release notes here on GitHub) manually.
2. Install the SEB setup (.msi) according to the OS platform (i.e. either x86 for a 32-bit or x64 for a 64-bit system).
