### ISSUE TITLE
Error Launching SEB with a Google meet URL

### ISSUE THREAD

**Issue by mbaddar** [SafeExamBrowser/seb-win-refactoring#498]
**Describe the Bug**
I am trying to test out a live proctoring session via google meet, I have set the launch URL in SEB configuration to a meet URL that I have started from another machine. However, when SEB launches to the meet URL I get a "You Can’t Join This Video Call" error.

When I change the launch URL to a quiz that contains a link to login to google account first (before starting the quiz), and another link to start the (Google meet) call. It starts without any issues  
**Steps to Reproduce**
1. Start an instant meeting on Google meet, copy the meet URL
2. Open SEB configuration, set the launch URL to the above
3. Launch SEB
4. A "You Can’t Join This Video Call" error is encountered

**Expected Behavior**
A prompt to enter the user name and join the meeting should be in place

**Screenshots**

**Version Information**
 - OS: Windows 10 Home
 - SEB-Version [e.g. SEB 3.4.0 (build 3.4.0.480)

**Comment by dbuechel** [comment]
Are there any error logs or other related information in the application logs of SEB? We don't use Google Meet and unfortunately do not have the capacity at the moment to investigate such issues further, unless there is a clear indication that the problem lies on SEB's side and not with Google Meet.

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
