### ISSUE TITLE
Check/Uncheck "Allow downloading and uploading files" does not lead to change availability of the options under it

### ISSUE THREAD

**Issue by tavaba** [SafeExamBrowser/seb-win-refactoring#533]
**Issue**: Check/Uncheck "Allow downloading and uploading files" does not lead to change availability of the options under it

**System Information:**
- Windows 10 x64 Enteprise
- SEB 3.4.1.505

**Steps to reproduce the behavior:**
1. Run "SEB Configuration Tools"
2. Open tab "Down/Uploads"
3. Check/Uncheck "Allow downloading and uploading files"

**Comment by dbuechel** [comment]
Your report is unfortunately not quite clear to me: What do you mean by "availability options under it", to what does "it" refer? And what error do you mean with step 4 "See error"?

**Comment by tavaba** [comment]
I'm very sorry for late response.
![Upload_Download_Settings](https://user-images.githubusercontent.com/50095576/207840756-d06e6bcd-38fb-4c5c-9a9f-ac7ef8f3a34d.png)
When I uncheck the option "Allow downloading and uploading files" (1), I can still setup the underlying options, such as "Choose download/upload directory", "Allow user to select custom download/upload directory"... (2)
This should be considered as an UI error.

**Comment by dbuechel** [comment]
Ah, I see. Yes, you're correct, that is not correct and should ideally be changed. But unfortunately, this is either way still the legacy configuration tool we took over from SEB 2.x and the plan would be to entirely rewrite it, but thus far we did not have the chance to do so due to ever-changing priorities and new feature requests. I might fix it in a spare minute, but it's likely that we'll have to live with this until we finally get around to rewrite the configuration tool.
