### ISSUE TITLE
VM Detection can be bypassed easily

### ISSUE THREAD

**Issue by marora1** [SafeExamBrowser/seb-win-refactoring#57]
The VM Detection in SEB only checks for Manufacturer's name and Mac address, these are things which can easily be manipulated both in VirtuallBox and VMWare. 

 In VMWare changing the manufacturer name from (“VMWare Inc.”) to anything else is enough to bypass the VM Detection; This can be done with the help of a simple edit in the VMX File of the VM

**SMBIOS.reflectHost = “True”** -- this changes the manufacturer name to that of the original machine,

Before:
![image](https://user-images.githubusercontent.com/75358863/100844380-cdad5580-34a1-11eb-9f9a-08e9a90ab0a5.png)
After:
![image](https://user-images.githubusercontent.com/75358863/100844403-d6059080-34a1-11eb-829d-9567de3bff09.png)
As you can see system manufacturer changes from VMWare Inc. to Acer which is sufficient to bypass the VM detection.

Steps for recreating:
1.Create a Win10 VM in VMWare
2. Open the vmx file in notepad and add the following on a new line **SMBIOS.reflectHost = "True"**
3. To verify if #2 worked, power on the VM and in CMD type :**systeminfo | findstr /C:”System Manufacturer**” it should the show your original PC's manufacturers name **(and not VMWare Inc.).**
4.Open SEB, the VM does not get detected.

Version info:
SEB 3.1.0
Windows 10 x64 Build 1863.1198
VM Detection was enabled in configuration file

![image](https://user-images.githubusercontent.com/75358863/100844995-92f7ed00-34a2-11eb-8a3b-9a9dd8136d22.png)

Thanks,
Ashish

**Comment by dbuechel** [comment]
Thanks for your report. You are absolutely right, it is relatively easy to circumvent this check. But unfortunately, there isn't much we can do at the moment. The reliable detection of virtual machines is incredibly complicated and error-prone, as we had to learn ourselves with false positive issues.
Due to limited developer resources, we currently don't have the time nor experience to attempt to improve this mechanism, so please allow me to close the issue for now. Rest assured that we have this item in our backlog as well. One thing to furhtermore keep in mind is the fact that BYOD exams will never be as secure as exams running in a managed / controlled environment. So if you need absolute control, we strongly recommend running exams in the latter manner.

**Comment by danschlet** [comment]
An additional comment: If you're conducting remote exams (as many now during Corona lockdowns), you could use a mobile device for remote proctoring which students would have to place diagonally behind them, so the camera films the screen and their hands on the keyboard (some companies have remote exam solutions using such a second camera view or they just use a video conferencing app on the mobile device). Then you can make remote exams a bit more secure, as you could potentially catch students who use virtual machines or just a hardware switch for an external monitor to switch to another computer during the exam (or who use a smart phone outside of the view of their webcam). But also such solutions would never be perfectly secure, even if you try to use a 360° camera. Still exams in an exam hall with human proctors walking around are more secure. Or just make good exams which students enjoy and are willing to be honest in, instead of wasting time trying to cheat.

**Comment by marora1** [comment]
Thanks Guys!, I Completely understand how difficult it is to detect VM's without false triggers, but as an initial
step could you please update the code to detect a wider set of VM's?
The current source can only detect: Azure, Hyper-V, Virtualbox, VMware, Parallels, Red Hat and Qemu
Could you make the list long enough so that at least no cheating can be done directly without any modifications?

**Comment by dbuechel** [comment]
If you have such a list and are willing to share it, we'll happily integrate it in the code. We must however insist that you thoroughly test these additions, as we need to prevent that people are running into false positives when they're trying to perform an exam.

**Comment by hoaivan** [comment]
What do you think about this: https://github.com/robsonfelix/VMDetector ?

**Comment by vseth1** [comment]
@hoaivan That repository hasn't been updated since 2017, It doesn't make sense to completely replace the VM detection with an external source, it may false trigger. The only solution is either to develop a better VM  detection inhouse, or to keep making imprhttps://github.com/vseth1ovements in the existing detection until it reaches a reliable stage.

**Comment by diegoara96** [comment]
A relatively straightforward option might be to add VMware's PCI Vendor [ven_15ad](https://devicehunt.com/view/type/pci/vendor/15AD) to this list but as @dbuechel  says, it should be tested very well to avoid false positives. https://github.com/SafeExamBrowser/seb-win-refactoring/blob/cb84fbd689493a0486b0f4373ab98674afd2b38e/SafeExamBrowser.SystemComponents/VirtualMachineDetector.cs#L21

**Comment by yuvarajucet** [comment]
how to do this in windows8.1

**Comment by verma-kunal** [comment]
How

> The VM Detection in SEB only checks for Manufacturer's name and Mac address, these are things which can easily be manipulated both in VirtuallBox and VMWare.
> 
> In VMWare changing the manufacturer name from (“VMWare Inc.”) to anything else is enough to bypass the VM Detection; This can be done with the help of a simple edit in the VMX File of the VM
> 
> **SMBIOS.reflectHost = “True”** -- this changes the manufacturer name to that of the original machine,
> 
> Before:
> ![image](https://user-images.githubusercontent.com/75358863/100844380-cdad5580-34a1-11eb-9f9a-08e9a90ab0a5.png)
> After:
> ![image](https://user-images.githubusercontent.com/75358863/100844403-d6059080-34a1-11eb-829d-9567de3bff09.png)
> As you can see system manufacturer changes from VMWare Inc. to Acer which is sufficient to bypass the VM detection.
> 
> Steps for recreating:
> 1.Create a Win10 VM in VMWare
> 2. Open the vmx file in notepad and add the following on a new line **SMBIOS.reflectHost = "True"**
> 3. To verify if #2 worked, power on the VM and in CMD type :**systeminfo | findstr /C:”System Manufacturer**” it should the show your original PC's manufacturers name **(and not VMWare Inc.).**
> 4.Open SEB, the VM does not get detected.
> 
> Version info:
> SEB 3.1.0
> Windows 10 x64 Build 1863.1198
> VM Detection was enabled in configuration file
> 
> ![image](https://user-images.githubusercontent.com/75358863/100844995-92f7ed00-34a2-11eb-8a3b-9a9dd8136d22.png)
> 
> Thanks,
> Ashish

which file to edit if are using Virtual Box ?

**Comment by dibyadas1033** [comment]
can the teachers know whether the students are changing the config into vm machine

**Comment by danschlet** [comment]
Yes, when using the ConfigKey or BrowserExamKey checks.

**Comment by marora1** [comment]
> can the teachers know whether the students are changing the config into vm machine

I don't know if their are any new code changes, but I used this with exam.net and none of my teachers got notified! As far as I know Config Key is only used to authenticate the SEB client, 

Their VM detection code is still the same, only checks for manufacturer's name and mac address!

**Comment by cutibmt01** [comment]
sorry , but where the vmx file.

**Comment by 13nz0** [comment]
Which file would be the correct one for virtualbox?


@hoaivan @marora1 @verma-kunal @dbuechel

**Comment by 22014360-Aqili-Azraqi** [comment]
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/133852177/eb6ba115-b17d-430c-a15e-58f6ec9645e8)
After i added the SMBIOS.reflectHost = “True” i lauched the VM but it would simply just disappear

**Comment by Neutx** [comment]
> ![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/133852177/eb6ba115-b17d-430c-a15e-58f6ec9645e8)
> After i added the SMBIOS.reflectHost = “True” i lauched the VM but it would simply just disappear
> 

Can you elaborate your issue?

**Comment by AyushGahtori** [comment]
> ![image](https://private-user-images.githubusercontent.com/133852177/251358420-eb6ba115-b17d-430c-a15e-58f6ec9645e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Njg2MzEsIm5iZiI6MTcxMzk2ODMzMSwicGF0aCI6Ii8xMzM4NTIxNzcvMjUxMzU4NDIwLWViNmJhMTE1LWIxN2QtNDMwYy1hMTVlLTU4ZjZlYzk2NDVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNDE4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGRlOGM0NDMwNWY1YjA2NzIwN2EzMDBjMzI4NWY2Y2MwZjBjZDVlMWJjN2FmZDM0ZjYwMDBlYTE4MjhmZjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HwCcGAispok7jJ_OzvCQCc4MVT8BVcEgHuoQprBT6Lw) After i added the SMBIOS.reflectHost = “True” i lauched the VM but it would simply just disappear

i have the same issue bro

**Comment by EMT-Shadow** [comment]
Does anyone have experience with a secure virtual machine solution for running exam proctoring? Looking for insights on using OWASP antidetect methods to mask VM usage and maintain undetected operation by proctors, while ensuring full access to system resources.

**Comment by Maxhem2** [comment]
Any updates on how to make it work?

**Comment by 13MrBlackCat13** [comment]
What's the point of this check if I can just fork it and remove this check or others?
