### ISSUE TITLE
Configure the SEB's start url dynamically.

### ISSUE THREAD

**Issue by lopezbertoni** [SafeExamBrowser/seb-win-refactoring#574]
**Is your feature request related to a problem? Please describe.**
I couldn't find a way to configure the start url for the SEB dynamically. Can this be done?
If not, can you please point me in a direction in which I can have a specific start url configured and distribute that. As far as I know, the only way to do it now is downloading a separate config file. 

**Describe the solution you'd like**
Be able to create a downloadable version of the SEB with a specific configuration dynamically. 
Or else, maybe pass some parameters to the executable when running it so that it overrides the stock configuration.

**Describe alternatives you've considered**
One alternative is to work around our flow so that all exams go through the same page, so we can have 1 distributable that we open and it automatically loads that page.

**Additional context**
Different exams have different requirements, so the ability to tell the SEB what start url to open dynamically would be super beneficial to our use case.

**Comment by dbuechel** [comment]
We have some information about integration of SEB in LMS as well as facilitating the starting of exams, please refer to https://safeexambrowser.org/developer/seb-integration.html.

One important aspect to mention here is that SEB has the possibility to reconfigure itself with new / different settings. So there definitely already is a way to accomplish the use case you're asking for, it may only be that you'd need to set up a system so that your students can reconfigure SEB according to the exam they need to take.
