### ISSUE TITLE
MAC Address Of System Info Not Being Loaded

### ISSUE THREAD

**Issue by dbuechel** [SafeExamBrowser/seb-win-refactoring#637]
I have realized that the following WMI query does not seem to work correctly on all systems: https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.SystemComponents/SystemInfo.cs#L222.

On my physical machine which I use for development, all `DNSDomain` property values are `null` when I remove the query condition `WHERE DNSDomain IS NOT NULL`, but if I run the same WMI query directly in a command prompt instance, I do get a valid `DNSDomain` property value for the physical network adapter of my system.

@diegoara96 Could you please have a look at the issue?

**Comment by dbuechel** [comment]
@Notselwyn FYI

**Comment by diegoara96** [comment]
It's been so long since I did this that I don't know if I can do much to help. On my current windows 11 machine it also returns null when querying wmic. If I change it to DNSHostName it returns the main network card but I don't know if it can work on other machines.

` Get-WmiObject -Query "select MACAddress,IPAddress FROM Win32_NetworkAdapterConfiguration WHERE DNSHostName is not null"`

**Comment by Notselwyn** [comment]
I believe that in my case the DNSDomain conditions is bugging the query, since none of my adapters have a DNSDomain even though they have a MAC address and are connected to a network.
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/68616630/72d8c1d6-0535-4ce6-83cc-9777df1c60e2)

**Comment by diegoara96** [comment]
@Notselwyn can you run the following command in a powershell ? On my machine it returns the main network adapter, it looks like something must have been updated in windows.

` Get-WmiObject -Query "select MACAddress,IPAddress FROM Win32_NetworkAdapterConfiguration WHERE DNSHostName is not null"`

**Comment by Notselwyn** [comment]
> Get-WmiObject -Query "select MACAddress,IPAddress FROM Win32_NetworkAdapterConfiguration WHERE DNSHostName is not null"

That appears to work indeed. It seems like I was checking the wrong WMI class (`Win32_NetworkAdapter` instead)
