### ISSUE TITLE
Fix for CORS (#46) broke key check on subdomain

### ISSUE THREAD

**Issue by jeroenhabets** [SafeExamBrowser/seb-win-refactoring#66]
The CORS issue of #46 was [fixed using a strict same domain check in SafeExamBrowser.Browser/Handlers/ResourceHandler.cs:123](https://github.com/SafeExamBrowser/seb-win-refactoring/commit/1cf9d53121d6cad073ee8e487dcbc3bc1aa72de4
) for SEB 3.1.1
`if (pageUrl?.Host?.Equals(requestUrl?.Host) == true)`

Our platform uses a subdomain for the API (e.g. api.domain.com for domain.com) and the fix above ignores any CORS headers.

For now we have advised the few customers that actively used the "Use Browser Exam Key and Config Key" functionality of SEB to disable it but it would be nice if subdomains (easy quickfix) or CORS headers (proper) would be supported again.

P.S. I am no CORS expert.

**Comment by danschlet** [comment]
Unfortunately the Chromium browser engine used in SEB made some changes in handling of these CORS requests (there is a closed GitHub issue explaining details), that's why we needed to make this change. We cannot revert this. You will have to change your implementation on the Browser Exam / Config Key check.

We will anyways introduce a new Javascript API in SEB to query the BEK/CK, instead of having to check the HTTP request headers. The newer WebKit browser engine (used in SEB for macOS/iOS) doesn't allow to change request headers anymore, and now also Chromium/Blink doesn't fully support request header modifications. So this is a dead end and needs to be replaced asap.

**Comment by danschlet** [comment]
Existing issues about the CORS issue (please always search existing issues before posting a new):

https://github.com/SafeExamBrowser/seb-win-refactoring/issues/56
https://github.com/SafeExamBrowser/seb-win-refactoring/issues/46

**Comment by jeroenhabets** [comment]
@danschlet I even referred to #46 ;) so I will not respond more to [your last commen](https://github.com/SafeExamBrowser/seb-win-refactoring/issues/66#issuecomment-753919448)t but more importantly:

Thank you for [your clear response before last](https://github.com/SafeExamBrowser/seb-win-refactoring/issues/66#issuecomment-753917860)!  That the current "Use Browser Exam Key and Config Key" functionality based on HTTP headers is a dead-end. As it also provides more clarity to us and our customers.

Hence I agree to this being closed as **Won't fix**.

**Comment by danschlet** [comment]
Sorry, I obviously didn't read your issue post properly... I guess you haven't understand [the answer](https://github.com/SafeExamBrowser/seb-win-refactoring/issues/46#issuecomment-734751995) of @dbuechel issue #46 fully, that's basically explaining why we had to remove the headers in subdomain requests.
