### ISSUE TITLE
Problem with display 0/1

### ISSUE THREAD

**Issue by rafa-tin** [SafeExamBrowser/seb-win-refactoring#718]
Hello, recently I had to take an exam, but something went wrong with the browser. I tried reinstalling the drivers, downloaded different versions of the browser. But the error is the same (presented below). Reinstalled Windows tried on 11, 10, 7, nothing came out.

**Version Information**
 - OS: [Windows 10 Home Version 22H2]
 - SEB-Version [SEB 3.5.0]

**Additional Context**
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/146753352/4560e0b4-cbbf-447c-8d06-588c2bbf19fe)

[2023-11-20_12h05m37s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13434520/2023-11-20_12h05m37s_Runtime.log)

**Comment by rafa-tin** [comment]
SEB 3.1.1 its work, but not accepted Web Cam

**Comment by dbuechel** [comment]
Can you please provide the log files of the affected session? They can be found under %LocalAppData%\SafeExamBrowser\Logs. In the past, there have been a few reports where the display detection did not work correctly due to a particular display driver, thus please make sure that you have installed the correct driver and that it is up to date.

**Comment by dbuechel** [comment]
Any updates here?

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
