### ISSUE TITLE
Display issue with Moodle quizzes using the Safe Exam Browser

### ISSUE THREAD

**Issue by Maherika** [SafeExamBrowser/seb-win-refactoring#740]
Hello,

We discovered quite an interesting bug in the interaction between Moodle 4.1 and SEB (Safe Exam Browser) (Latest version 3.5 and earlier):

When we access a quiz as an instructor, both the quiz page and the quiz itself are displayed in our standard design (Boost-Union):
![SEB Test_Teacher](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/152861127/b9227128-f774-42e0-b47f-dc673c47f123)

If we open the same quiz from a student perspective (whether via a test account or by switching), The design is not displayed as expected in the Boost Union design, but is significantly reduced (and this is before the SEB has even started)
![SEB Test_Student](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/152861127/51558ebe-7c78-494d-a977-7968ddd2ec28)
:

The issue also occurs within the SEB and is, of course, very confusing for the students. Is this problem known? This issue is also currently being discussed in the SIG E-Assessment group: https://moodle.hu-berlin.de/mod/forum/discuss.php?d=941694

Thanks and best regards

Mareike

**Comment by danschlet** [comment]
In Moodle there is a special secure quiz layout defined, which is used when activating SEB support for a quiz (I guess it is also used for the other assessment modes like that not really very secure full screen popup in "Extra restrictions on attempts"). Obviously in a quiz, navigation to other sections of Moodle has to be disabled.  I asked our Moodle developer to clarify this further.

Are you aware of that? Or did I misunderstand your question?

**Comment by nexterday** [comment]
Hi @Maherika the secure layout is part of boost theme (core) and boost union inherits that layout (has no custom layout). We have submitted a fix that suits our institute and it go accepted and its now in integration phase (for 4.0+). if you would like to make it more fancier with custom components/headers etc, and because you are using boost union, I recommend you contact the developers in their repo with what features you would like to add. 

Link to reported and fixed issue can be found here: https://tracker.moodle.org/browse/MDL-74836

**Comment by danschlet** [comment]
Thank you @nexterday for the clarification. So in short, the quiz description is missing in quizzes which are configured to be accessible only with SEB (I assume that this is only the case when accessing the quiz in a student role, as teachers or admins can always access quizzes without SEB, even if configured to require SEB).

@Maherika is this the issue you were referring to? Or are you missing other elements or formatting of the "normal", not secure quiz UI?

**Comment by nexterday** [comment]
Thats true @danschlet - basically since moodle 4.0 they shaved almost everything in secure layout (seb layout when a student is logged in). What @Maherika can do is:
1. Go to /admin/settings.php?section=themesettings and enable the language, logged in user tick boxes to show in header
2. Cherry pick the fix direct from moodle github or simply wait for integration and make an update to their moodle so they can see the heading and description so everything looks “normal” as it used to look before.

**Comment by Maherika** [comment]
@danschlet if I have understood correctly, the reduced Design/layout of a test with SEB is also desired even before the SEB has started. What I was mainly missing was the "normal" layout of the test. The design/layout will change again within the SEB anyway. @nexterday thank you for the tips. I am coordinating with our service provider to determine whether this described fix is also an option for us.

**Comment by nexterday** [comment]
@Maherika the shaving was done by Tim without referring to seb or anyone - we woke up on 4.0 with new secure layout that removed “supposedly unnecessary elements” on a better be safe than sorry basis (you can read the long debate in the tracker). So we have nothing to do with it, it is just that deep integration happened in parallel by pure coincedence.

integration is in final stage so all we can do is to pray that Tim has a mercy on us and push that blue button :-)

**Comment by dbuechel** [comment]
I shall close the issue for the time being, please do feel free to reopen it should new issues emerge.
