### ISSUE TITLE
please get the software working on linux please

### ISSUE THREAD

**Issue by Xeane74** [SafeExamBrowser/seb-win-refactoring#742]
well i had to remove my whole operating sys to install propitiatory virus called windows to run the browser for a test. sooo...... please can you get it working on linux. pretty please.   
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/105660154/d1b57c2a-0742-45cd-8ba1-38f33853bae3)

**Comment by dbuechel** [comment]
We have covered this topic extensively in other issues and discussion, see e.g. #44, #91, #646 or #708. In short: Unfortunately not, unless you have some $100'000 lying around which you could send our way so that we can hire a dedicated Linux developer.

Apart from that, you could have installed Windows on an external hard disk or memory stick, or then set up a dual boot system in order to perform the exam under Windows whilst retaining your Linux system.

**Comment by Xeane74** [comment]
Thanks for responding.
I thought that would be the answer but it was worth a try.XD
I have opted to dual boot for my future tests.
Thanks once again.
