### ISSUE TITLE
SEB launching to black screen 

### ISSUE THREAD

**Issue by shychowd** [SafeExamBrowser/seb-win-refactoring#760]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
Safe Exam Browser is launching to a blank black screen on launch. 

**Steps to Reproduce**
1. Launch SEB

**Expected Behavior**
Should land on the default landing page or the URL provided by the configuration file

**Screenshots**

**Version Information**
 - OS: Windows 10 Enterprise
 - SEB-Version [e.g. SEB 3.0.1]

**Additional Context**
We are trying to build our own custom fork of SEB. However we are finding that even with none of our code changes, the SEB build installed does not launch correctly. It opens to a blank black screen, and the only unexpected message in the logs is from the runtime:

`WARNING: [DesktopMonitor] Failed to get currently active desktop!`

If relevant: we have a code signing certificate that we are using to sign the .dll files, setup.msi and setupbundle.exe. Otherwise we are building the code from the master branch of seb-win-refactoring with no changes.

**Comment by dbuechel** [comment]
Support for customization of SEB is reserved for members of the SEB Alliance (see https://safeexambrowser.org/alliance/fees.html). Thus, please consider joining the alliance as we cannot provide detailed support out of fairness to the members paying (substantial) membership fees.

In general, you only need to ensure the following in order to be able to correctly build and run SEB from within Visual Studio:

- Always rebuild the entire solution.
- Make sure that all runtime dependencies are correctly installed resp. integrated (e.g. NuGet packages).
- Make sure that the runtime component is set as startup project.
