### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [SafeExamBrowser/seb-win-refactoring#78]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Safe Exam Browser on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by danschlet** [comment]
Flatpak seems to be an interesting option for distributing applications to various Linux distributions. 

But that doesn’t solve the main problem: We would first need a Linux version of SEB. To secure a system, you need code specific to that operating system, including its desktop manager and various other system components.

This realistically means you need a dedicated developer with very good Linux experience. That person would need to do the initial development, but then constantly work on maintaining and supporting that version, improving its security etc.

We’re not commercial and also first would need funding for an additional developer. If any large organization is willing to fund a developer, there will be a Linux version of SEB, otherwise there won’t. It’s as simple as that.
