### ISSUE TITLE
SEB is unusable on Windows tablet

### ISSUE THREAD

**Issue by mbalous** [SafeExamBrowser/seb-win-refactoring#781]
**Describe the Bug**
On screen keyboard doesn't appear when entering text field on website that is used for exam authentication. It is therefore unusable and the user can't proceed further. This is essentially blocking all windows tablet users from using this software which is a serious limitation in my mind.

**Steps to Reproduce**
1. Start exam which requires submitting a login page
2. Click on text field

**Expected Behavior**
On screen keyboard appears

**Screenshots**
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/10358985/f3a7beee-c632-4b98-a2b1-c48f2e1d0d53)

**Version Information**
 - OS Version:  Windows 11 10.0.22621 N/A Build 22621
 - Safe Exam Browser, Version 3.6.0 (x64), Build 3.6.0.633

**Device**
Microsoft Surface Pro 7

**Comment by mbalous** [comment]
I have just read the documentation at https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane about _Kiosk mode_ where it mentions that on-screen keyboard is not available in _Create new desktop_ mode. I think that's a major drawback of that mode and perhaps it shouldn't be default? I don't think it's smart to by default ban all Windows tablet users from using the software.

**Comment by dbuechel** [comment]
Yes indeed, that is an existing limitation which actually has its roots in the operating system itself. Therefore, if you need to use tablet mode or an on-screen keyboard, please use kiosk mode Disable Explorer Shell.

**Comment by dbuechel** [comment]
Also, please note that MSFT has changed the implementation resp. framework they used for the on-screen keyboard to an UWP app (which are incompatible with both of SEB's kiosk modes). So the current default implementation of the on-screen keyboard is by default not usable within SEB.

However, it used to be the case that one could re-activate the old (non-UWP) implementation using the following registry key: `HKCU\Software\Microsoft\TabletTip\1.7\DisableNewKeyboardExperience = 1 `. If that's still the case, it would obviously be required in order to use the on-screen keyboard within SEB.
