### ISSUE TITLE
webRTC not granted

### ISSUE THREAD

**Issue by HilmanKhairr** [SafeExamBrowser/seb-win-refactoring#785]
have an app that need to allow webRTC for camera and microphone. In 2.4.1 its works with automatically granted permission, but in 3.6.0 its not work and nothing happened.

**Expected Behavior**
should allow webRTC

**Version Information**
 - OS: Windows 10
 - SEB-3.6.0

**Comment by dbuechel** [comment]
WebRTC is enabled since quite a few release versions and it (used to) work without issues. There recently has been a related report though (see #471), so you might want to check whether it is relevant for your case. Apart from that, please provide a way to reproduce (step-by-step instructions) the exact problem you're experiencing, otherwise there's not much we can do.
