### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by linnea1234** [SafeExamBrowser/seb-win-refactoring#830]
Hello,
 I am receiving this error when I try to install

"The feature you are trying to install is on a network resource that is unavailable"

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/164215863/e1fe060e-49f4-45b9-8b73-287ccdfe3c3c)

Thanks for your help

**Comment by NekoJonez** [comment]
I have seen this behaviour on my student/teachers laptops. We use Microsoft Endpoint to configure them and we require to install Safe Exam Browser. So it gets pushed from our server.
Also, I have noticed similar behaviour when SEB is already installed.

**Comment by dbuechel** [comment]
This most likely is not an issue with SEB or its installer. Windows caches installer packages to be able to later on repair or uninstall a software. If such a cached package is however unavailable (e.g. because you deleted it), you'll need to manually provide it in order to be able to continue. In your particular case, you'd need to locate the installer package "vc_runtimeMinimum_x64.msi" (which is not part of the SEB installer, we package "vc_redist.x64.exe") as is specified in the error message itself.
