### ISSUE TITLE
Version without proprietary modules

### ISSUE THREAD

**Issue by fkohrt** [SafeExamBrowser/seb-win-refactoring#89]
**Is your feature request related to a problem? Please describe.**

At a German national competition we have decided to use SEB for BYOD assessments because it is not a proprietary solution that we ask our students to install. Now we saw in the [roadmap](https://safeexambrowser.org/about_roadmap_en.html) that it is planned to integrate binary blobs, making SEB in part proprietary.

**Describe the solution you'd like**

A version without any proprietary, code-obfuscated binary blobs.

**Describe alternatives you've considered**

None, we wouldn't be able to use SEB anymore.

**Additional context**

BYOD scenarios and proctoring software are a sensitive issue for us as we need to justify our technological requirements to students and parents.

**Comment by danschlet** [comment]
For the Windows and Mac versions of SEB we have not yet decided about details of increasing the security of SEB for BYOD exams. We will consider your feature request. We nevertheless are getting many contrary requests, which suspect that SEB is too easy to manipulate because the full code is open source, especially in BYOD environments where the integrity of the used SEB version cannot be verified.

What is already clear, that any solution would allow to build SEB versions without the binary security module and maintain its functionality (just missing some of the increased security functions which would require the module).

We might also consider a similar solution that Mozilla uses for the [DRM module in Firefox](https://support.mozilla.org/en-US/kb/enable-drm).
