### ISSUE TITLE
Command Line Utility in Windows 11 doesn't work with Safe Browser allowed application

### ISSUE THREAD

**Issue by allenzx2005** [SafeExamBrowser/seb-win-refactoring#919]
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**
Having added "Windows Command Line Utility" to the allowed application list. However, when entered the safe exam browser session, and then when clicked on the command line utility, it would not launch (actually it opened but is instead on the Windows 11 desktop). This used to work flawlessly with windows 10 back then.

**Steps to Reproduce**
1. add cmd from : "C:\Windows\System32\cmd.exe" into the allowed application list
2. Launch from inside of safe browser, cmd.exe launches but is hidden behind the safe browser. cmd.exe runs on the windows desktop.

**Expected Behavior**
 Launch cmd from inside of safe browser, cmd.exe launches and shows up inside the safe browser
**Screenshots**
If applicable, add screenshots to help explain your p
<img width="1041" alt="Screenshot 2024-06-17 105024" src="https://github.com/SafeExamBrowser/seb-win-refactoring/assets/173093341/ae0ba248-a15d-4c4a-bfbf-290a6e50058e">
roblem.

**Version Information**
 - OS: [e.g. Windows 10 Professional, Version 1803]
 - SEB-Version [e.g. SEB 3.0.1]

**Additional Context**

**Comment by danschlet** [comment]
Hmm, for what else than attempting to manipulate SEB would you try to allow the command line utility to run during an exam?

**Comment by dbuechel** [comment]
@allenzx2005 Did you add the application via the button "Choose Application..."? It may be that the paramters like signature, path and/or original name are missing or incorrect.

If that still doesn't work, please provide the log files of the affected session(s) in order to investigate why SEB doesn't start or permit the console application.

**Comment by allenzx2005** [comment]
Hi Daniel,

Yes, cmd.exe was added correctly in Safe browser. Other applications, like powershell.exe works perfectly. In fact, cmd.exe worked flawlessly with safe browser back in Windows 10. I think it is something with Windows 11 not playing nice. When launching cmd.exe from inside the browser, cmd.exe does launch, but is hidden behind the browser and we would quit the browser to see it.

I have attached the logs. 

thank you so much!
allen
[2024-06-24_13h29m36s_Browser.log](https://github.com/user-attachments/files/15960992/2024-06-24_13h29m36s_Browser.log)
[2024-06-24_13h29m36s_Client.log](https://github.com/user-attachments/files/15960993/2024-06-24_13h29m36s_Client.log)
[2024-06-24_13h29m36s_Runtime.log](https://github.com/user-attachments/files/15960994/2024-06-24_13h29m36s_Runtime.log)

**Comment by dbuechel** [comment]
I think the issue is that under Windows 11 (starting from version 22H2), the console application will by default be started in the new Windows Terminal application: https://support.microsoft.com/en-us/windows/command-prompt-and-windows-powershell-for-windows-11-6453ce98-da91-476f-8651-5c14d5777c20.

Most likely, the new terminal application is incompatible with SEB's kiosk modes and/or tries to start a new explorer instance as can be seen in the log. Thus please try any of the solution attempts listed in the above linked article from Microsoft.
