### ISSUE TITLE
COmpatibility issues with Windows Integrated Authentication (WIA)

### ISSUE THREAD

**Issue by MattiasAtATEA** [SafeExamBrowser/seb-win-refactoring#925]
Our students are authenticated with user id and password before they access the national assessment test, which is provided by Skolverket in Sweden.

We use the latest version of Active Directory Services (AD FS) for student authentication. The students have either a Windows 10/11 PC or an iPad.

The default AD FS-policy is to use Windows Integrated Authentication (WIA) for all users on the local network (internal), and FORMS for all users who connect over Internet (external).

The problem is that the WIA-page does not load on any Windows PCs using SEB 3.7.0, all those students get a white page. It works fine however on iPads with SEB 3.3.2, and the FORMS-page works fine on PC.

Our workaround for now is that we have removed Firefox and Mozilla/5.0 from the WIASupportedUserAgent setting in AD FS, and that solves the problem for us. FORMS works fine on SEB 3.7.0 but not WIA and that is consistent for all our PCs.

We are migrating away from AD FS så right now the workaround i sufficient for us.

**Comment by dbuechel** [comment]
I can't see anything related in the browser or client logs. I'm unfortunately not familiar with WIA nor AD FS, so I can't help much there, but SEB 3.x is using Chromium not Firefox as integrated browser engine (SEB 2.x used Firefox).

Apart from that, I'd need a way to reproduce the issue (including step-by-step instructions), otherwise there's most likely not much I can do to help.
