### ISSUE TITLE
App hangs and Error message due to Windows API change

### ISSUE THREAD

**Issue by HunterMSFT** [SafeExamBrowser/seb-win-refactoring#935]
> [!IMPORTANT]

**Describe the Bug**
Windows now requires location permissions in order to access Wi-Fi scan APIs. This change appears to impact Safe Exam Browser, which is throwing an error when it cannot access these APIs. There are details about this change and the actions an app should take here: 
https://learn.microsoft.com/en-us/windows/win32/nativewifi/wi-fi-access-location-changes 

**Steps to Reproduce**
	1. Install any Windows Insider build
	2. Turn off location in Settings>privacy & security> Location
	4. Launch Safe Exam Browser
5. Observe "Fails to launch the app with "Session start error" post upgrade"

**Expected Behavior**
Safe Exam Browser should handle the case where location permission is not granted, and not throw an error. 

**Screenshots**
![image](https://github.com/user-attachments/assets/0d87faf6-edf7-417d-ac74-f046c4f89b28)
[REPRO_Start_Error_logs.zip](https://github.com/user-attachments/files/16183865/REPRO_Start_Error_logs.zip)

**Version Information**
 - OS: Windows 11 24H2
 - SEB-Version 3.7.1, maybe others

**Additional Context**
This change has been in Windows Insider builds since October 2023 https://blogs.windows.com/windows-insider/2023/10/18/announcing-windows-11-insider-preview-build-25977-canary-channel/

**Comment by dbuechel** [comment]
Thanks for the report. I actually already stumbled upon the change by mere coincidence while reading the above linked documentation while rewriting the network adapter for the upcoming release version 3.8.0. The issue should thus hopefully be resolved, as the new implementation explicitly requests access as is recommend due to the changes.

Could you please try the latest beta build for SEB 3.8.0 to verify that it works as intended? The direct link to the current build is https://sebdev.ethz.ch/api/buildjobs/g3txpgcyf7aav1ol/artifacts/SEB_3.8.0.711_SetupBundle.exe.

**Comment by HunterMSFT** [comment]
That is great, we will test with the new app version and see if the issue persists. Thanks!

**Comment by dbuechel** [comment]
Excellent, that would be great, thanks as well.

**Comment by HunterMSFT** [comment]
We've confirmed that the issue no longer occurs in the latest beta version of the app 3.8.0.711

**Comment by dbuechel** [comment]
Great, thanks for the testing and feedback. It should actually work as is recommended in the documentation linked above, in that SEB asks for the required location permission and then acts accordingly.
