### ISSUE TITLE
SEB 3.7.1.704 Crash

### ISSUE THREAD

**Issue by 28Smiles** [SafeExamBrowser/seb-win-refactoring#973]
**Describe the Bug**
SEB fatal crash to desktop during examination.

**Steps to Reproduce**
Unknown

**Screenshots**

**Version Information**
 - OS: Windows 10
 - SEB-Version 3.7.1.704

** Logs **
[2024-09-13_15h36m15s_Browser.log](https://github.com/user-attachments/files/17009692/2024-09-13_15h36m15s_Browser.log)
[2024-09-13_15h36m15s_Client.log](https://github.com/user-attachments/files/17009693/2024-09-13_15h36m15s_Client.log)
[2024-09-13_15h36m15s_Runtime.log](https://github.com/user-attachments/files/17009694/2024-09-13_15h36m15s_Runtime.log)
[2024-09-13_15h36m15s_Events.csv](https://github.com/user-attachments/files/17009712/2024-09-13_15h36m15s_Events.csv)

**Comment by dbuechel** [comment]
Please elaborate when resp. what you were doing when SEB crashed (the application logs show that Microsoft Edge has been started numerous times). We need a reliable way to reproduce the crash, otherwise there is not much we can do as the application logs only reveal that the inter-process communication of SEB's application components had failed.

**Comment by 28Smiles** [comment]
The Error occurred during an examination, I occurred on 1 out of 50 devices with the exact same configuration. We cant reproduce the crash reliably. Is there any measure we can apply to get better more reliable logging? Is Microsoft Edge starting/terminating normal?

**Comment by dbuechel** [comment]
> Is Microsoft Edge starting/terminating normal?

During an exam most likely not. Albeit that it could have been an auto-update mechanism or some other form of web application (activity) that caused Edge to start.

**Comment by dbuechel** [comment]
The event logs show a component of SEB's internal browser engine failing; it could have been a crash caused by the browser engine, but then again, that can only be investigated further with a reliable way of reproducing the issue. And if it was a one-time issue, then it likely does not merit further investigation.
