### ISSUE TITLE
Microsoft Visual C++ 2015 installation error

### ISSUE THREAD

**Issue by R2D2byBest** [SafeExamBrowser/seb-win-refactoring#999]
Hi,

I have users (2 at the moment) who are getting stuck with this error (w11)
![image](https://github.com/user-attachments/assets/316109fc-e6e8-42a3-9da2-a2c5a36a1def)

They have enough disk space, I just wanted to know if anyone has had the problem and identify a solution.

Thanks

**Comment by NekoJonez** [comment]
This might be related to #967 
But I have been this going wrong if Windows Update or the Windows Installer service is busy. Try to run the installer right after boot.

**Comment by dbuechel** [comment]
The message indicates that another installation is ongoing, so please make sure that you do not attempt to install various software products concurrently. Also, you may want to try installing this particular runtime dependency manually before retrying to install SEB (see the release notes for the download links).

Apart from that, if the Visual C++ redistributable (a Micorsoft product) fails to install, you'd need to search the Microsoft resource or resp. contact them in order to resolve it.
